/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface BatchInvoice {
    extractedFields?: ExtractedFields;
    invoiceId: bigint;
    isDuplicate: boolean;
    invoiceNumber: string;
    batchId: bigint;
    vendorName: string;
    isAutoMapped: boolean;
}
export interface ExportData {
    columnMappings: Array<[string, string]>;
    invoiceData: Array<InvoiceProcessingResult>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ExcelTemplate {
    id: bigint;
    blob: ExternalBlob;
    userId: Principal;
    columnHeaders: Array<string>;
    filename: string;
    uploadDate: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface InvoiceProcessingResult {
    status: {
        __kind__: "fail";
        fail: string;
    } | {
        __kind__: "success";
        success: null;
    };
    extractedFields?: ExtractedFields;
    invoiceId: bigint;
    vendorName: string;
}
export interface ProcessedInvoiceInput {
    blob: ExternalBlob;
    filename: string;
}
export interface Batch {
    status: BatchStatus;
    invoiceCount: bigint;
    userId: Principal;
    createdAt: Time;
    batchId: bigint;
}
export interface ExtractedFields {
    subtotalAmount: string;
    invoiceDate: string;
    invoiceNumber: string;
    totalAmount: string;
    gstTaxId: string;
    vendorName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface VendorTemplate {
    user: Principal;
    fieldMappings: Array<[string, string]>;
    vendorName: string;
}
export enum BatchStatus {
    active = "active",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInvoiceToBatch(batchId: bigint, blob: ExternalBlob, filename: string): Promise<BatchInvoice | null>;
    archiveBatch(batchId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    autoApplyVendorTemplateForBatch(batchId: bigint, vendorName: string): Promise<bigint>;
    checkDuplicateInBatch(batchId: bigint, vendorName: string, invoiceNumber: string): Promise<boolean>;
    createBatch(): Promise<bigint>;
    createVendorTemplate(vendorName: string, fieldMappings: Array<[string, string]>): Promise<void>;
    deleteVendorTemplate(vendorName: string): Promise<void>;
    exportBatchData(batchId: bigint, columnHeaders: Array<string>): Promise<ExportData | null>;
    getBatchDetails(batchId: bigint): Promise<{
        batch: Batch;
        invoices: Array<BatchInvoice>;
    } | null>;
    getBatchInvoices(batchId: bigint): Promise<Array<BatchInvoice>>;
    getBatches(status: BatchStatus | null): Promise<Array<Batch>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExcelTemplateDetails(templateId: bigint): Promise<ExcelTemplate | null>;
    getExcelTemplates(): Promise<Array<ExcelTemplate>>;
    getInvoiceDetails(invoiceId: bigint): Promise<InvoiceProcessingResult | null>;
    getInvoices(): Promise<Array<InvoiceProcessingResult>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVendorTemplate(vendorName: string): Promise<VendorTemplate | null>;
    isCallerAdmin(): Promise<boolean>;
    listVendorTemplates(): Promise<Array<VendorTemplate>>;
    prepareExportData(invoiceIds: Array<bigint>, columnMappings: Array<[string, string]>): Promise<ExportData | null>;
    processBatchSequentially(batchId: bigint, invoiceBlobs: Array<ProcessedInvoiceInput>): Promise<Array<BatchInvoice> | null>;
    processInvoice(blob: ExternalBlob, filename: string, _vendorName: string): Promise<InvoiceProcessingResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBatchInvoiceMapping(batchId: bigint, invoiceId: bigint, fieldMappings: {
        subtotalAmount: string;
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: string;
        gstTaxId: string;
        vendorName: string;
    }): Promise<void>;
    updateVendorTemplate(vendorName: string, fieldMappings: Array<[string, string]>): Promise<void>;
    uploadExcelTemplate(blob: ExternalBlob, filename: string, columnHeaders: Array<string>): Promise<bigint>;
}
import type { Batch as _Batch, BatchInvoice as _BatchInvoice, BatchStatus as _BatchStatus, ExcelTemplate as _ExcelTemplate, ExportData as _ExportData, ExternalBlob as _ExternalBlob, ExtractedFields as _ExtractedFields, InvoiceProcessingResult as _InvoiceProcessingResult, ProcessedInvoiceInput as _ProcessedInvoiceInput, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VendorTemplate as _VendorTemplate, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInvoiceToBatch(arg0: bigint, arg1: ExternalBlob, arg2: string): Promise<BatchInvoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvoiceToBatch(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvoiceToBatch(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async archiveBatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveBatch(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async autoApplyVendorTemplateForBatch(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.autoApplyVendorTemplateForBatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoApplyVendorTemplateForBatch(arg0, arg1);
            return result;
        }
    }
    async checkDuplicateInBatch(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkDuplicateInBatch(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkDuplicateInBatch(arg0, arg1, arg2);
            return result;
        }
    }
    async createBatch(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBatch();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBatch();
            return result;
        }
    }
    async createVendorTemplate(arg0: string, arg1: Array<[string, string]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendorTemplate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendorTemplate(arg0, arg1);
            return result;
        }
    }
    async deleteVendorTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendorTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendorTemplate(arg0);
            return result;
        }
    }
    async exportBatchData(arg0: bigint, arg1: Array<string>): Promise<ExportData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.exportBatchData(arg0, arg1);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportBatchData(arg0, arg1);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchDetails(arg0: bigint): Promise<{
        batch: Batch;
        invoices: Array<BatchInvoice>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchDetails(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchDetails(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchInvoices(arg0: bigint): Promise<Array<BatchInvoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchInvoices(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchInvoices(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatches(arg0: BatchStatus | null): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatches(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatches(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExcelTemplateDetails(arg0: bigint): Promise<ExcelTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExcelTemplateDetails(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExcelTemplateDetails(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExcelTemplates(): Promise<Array<ExcelTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExcelTemplates();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExcelTemplates();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceDetails(arg0: bigint): Promise<InvoiceProcessingResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceDetails(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceDetails(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoices(): Promise<Array<InvoiceProcessingResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorTemplate(arg0: string): Promise<VendorTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorTemplate(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorTemplate(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listVendorTemplates(): Promise<Array<VendorTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVendorTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVendorTemplates();
            return result;
        }
    }
    async prepareExportData(arg0: Array<bigint>, arg1: Array<[string, string]>): Promise<ExportData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.prepareExportData(arg0, arg1);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.prepareExportData(arg0, arg1);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async processBatchSequentially(arg0: bigint, arg1: Array<ProcessedInvoiceInput>): Promise<Array<BatchInvoice> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.processBatchSequentially(arg0, await to_candid_vec_n43(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processBatchSequentially(arg0, await to_candid_vec_n43(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async processInvoice(arg0: ExternalBlob, arg1: string, arg2: string): Promise<InvoiceProcessingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processInvoice(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_InvoiceProcessingResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processInvoice(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_InvoiceProcessingResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBatchInvoiceMapping(arg0: bigint, arg1: bigint, arg2: {
        subtotalAmount: string;
        invoiceDate: string;
        invoiceNumber: string;
        totalAmount: string;
        gstTaxId: string;
        vendorName: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatchInvoiceMapping(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatchInvoiceMapping(arg0, arg1, arg2);
            return result;
        }
    }
    async updateVendorTemplate(arg0: string, arg1: Array<[string, string]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendorTemplate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendorTemplate(arg0, arg1);
            return result;
        }
    }
    async uploadExcelTemplate(arg0: ExternalBlob, arg1: string, arg2: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadExcelTemplate(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadExcelTemplate(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
}
function from_candid_BatchInvoice_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchInvoice): BatchInvoice {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BatchStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchStatus): BatchStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Batch_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Batch): Batch {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExcelTemplate_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExcelTemplate): Promise<ExcelTemplate> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ExportData_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportData): ExportData {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InvoiceProcessingResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceProcessingResult): InvoiceProcessingResult {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtractedFields]): ExtractedFields | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExportData]): ExportData | null {
    return value.length === 0 ? null : from_candid_ExportData_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        batch: _Batch;
        invoices: Array<_BatchInvoice>;
    }]): {
    batch: Batch;
    invoices: Array<BatchInvoice>;
} | null {
    return value.length === 0 ? null : from_candid_record_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExcelTemplate]): Promise<ExcelTemplate | null> {
    return value.length === 0 ? null : await from_candid_ExcelTemplate_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceProcessingResult]): InvoiceProcessingResult | null {
    return value.length === 0 ? null : from_candid_InvoiceProcessingResult_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VendorTemplate]): VendorTemplate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_BatchInvoice>]): Array<BatchInvoice> | null {
    return value.length === 0 ? null : from_candid_vec_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BatchInvoice]): BatchInvoice | null {
    return value.length === 0 ? null : from_candid_BatchInvoice_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    extractedFields: [] | [_ExtractedFields];
    invoiceId: bigint;
    isDuplicate: boolean;
    invoiceNumber: string;
    batchId: bigint;
    vendorName: string;
    isAutoMapped: boolean;
}): {
    extractedFields?: ExtractedFields;
    invoiceId: bigint;
    isDuplicate: boolean;
    invoiceNumber: string;
    batchId: bigint;
    vendorName: string;
    isAutoMapped: boolean;
} {
    return {
        extractedFields: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.extractedFields)),
        invoiceId: value.invoiceId,
        isDuplicate: value.isDuplicate,
        invoiceNumber: value.invoiceNumber,
        batchId: value.batchId,
        vendorName: value.vendorName,
        isAutoMapped: value.isAutoMapped
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    columnMappings: Array<[string, string]>;
    invoiceData: Array<_InvoiceProcessingResult>;
}): {
    columnMappings: Array<[string, string]>;
    invoiceData: Array<InvoiceProcessingResult>;
} {
    return {
        columnMappings: value.columnMappings,
        invoiceData: from_candid_vec_n18(_uploadFile, _downloadFile, value.invoiceData)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        fail: string;
    } | {
        success: null;
    };
    extractedFields: [] | [_ExtractedFields];
    invoiceId: bigint;
    vendorName: string;
}): {
    status: {
        __kind__: "fail";
        fail: string;
    } | {
        __kind__: "success";
        success: null;
    };
    extractedFields?: ExtractedFields;
    invoiceId: bigint;
    vendorName: string;
} {
    return {
        status: from_candid_variant_n21(_uploadFile, _downloadFile, value.status),
        extractedFields: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.extractedFields)),
        invoiceId: value.invoiceId,
        vendorName: value.vendorName
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    batch: _Batch;
    invoices: Array<_BatchInvoice>;
}): {
    batch: Batch;
    invoices: Array<BatchInvoice>;
} {
    return {
        batch: from_candid_Batch_n24(_uploadFile, _downloadFile, value.batch),
        invoices: from_candid_vec_n28(_uploadFile, _downloadFile, value.invoices)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BatchStatus;
    invoiceCount: bigint;
    userId: Principal;
    createdAt: _Time;
    batchId: bigint;
}): {
    status: BatchStatus;
    invoiceCount: bigint;
    userId: Principal;
    createdAt: Time;
    batchId: bigint;
} {
    return {
        status: from_candid_BatchStatus_n26(_uploadFile, _downloadFile, value.status),
        invoiceCount: value.invoiceCount,
        userId: value.userId,
        createdAt: value.createdAt,
        batchId: value.batchId
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    userId: Principal;
    columnHeaders: Array<string>;
    filename: string;
    uploadDate: _Time;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    userId: Principal;
    columnHeaders: Array<string>;
    filename: string;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value.blob),
        userId: value.userId,
        columnHeaders: value.columnHeaders,
        filename: value.filename,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fail: string;
} | {
    success: null;
}): {
    __kind__: "fail";
    fail: string;
} | {
    __kind__: "success";
    success: null;
} {
    return "fail" in value ? {
        __kind__: "fail",
        fail: value.fail
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    archived: null;
}): BatchStatus {
    return "active" in value ? BatchStatus.active : "archived" in value ? BatchStatus.archived : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceProcessingResult>): Array<InvoiceProcessingResult> {
    return value.map((x)=>from_candid_InvoiceProcessingResult_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BatchInvoice>): Array<BatchInvoice> {
    return value.map((x)=>from_candid_BatchInvoice_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Batch>): Array<Batch> {
    return value.map((x)=>from_candid_Batch_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExcelTemplate>): Promise<Array<ExcelTemplate>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExcelTemplate_n37(_uploadFile, _downloadFile, x)));
}
function to_candid_BatchStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchStatus): _BatchStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ProcessedInvoiceInput_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProcessedInvoiceInput): Promise<_ProcessedInvoiceInput> {
    return await to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchStatus | null): [] | [_BatchStatus] {
    return value === null ? candid_none() : candid_some(to_candid_BatchStatus_n30(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    filename: string;
}): Promise<{
    blob: _ExternalBlob;
    filename: string;
}> {
    return {
        blob: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.blob),
        filename: value.filename
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchStatus): {
    active: null;
} | {
    archived: null;
} {
    return value == BatchStatus.active ? {
        active: null
    } : value == BatchStatus.archived ? {
        archived: null
    } : value;
}
async function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProcessedInvoiceInput>): Promise<Array<_ProcessedInvoiceInput>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ProcessedInvoiceInput_n44(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
