/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Batch {
  'status' : BatchStatus,
  'invoiceCount' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'batchId' : bigint,
}
export interface BatchInvoice {
  'extractedFields' : [] | [ExtractedFields],
  'invoiceId' : bigint,
  'isDuplicate' : boolean,
  'invoiceNumber' : string,
  'batchId' : bigint,
  'vendorName' : string,
  'isAutoMapped' : boolean,
}
export type BatchStatus = { 'active' : null } |
  { 'archived' : null };
export interface ExcelTemplate {
  'id' : bigint,
  'blob' : ExternalBlob,
  'userId' : Principal,
  'columnHeaders' : Array<string>,
  'filename' : string,
  'uploadDate' : Time,
}
export interface ExportData {
  'columnMappings' : Array<[string, string]>,
  'invoiceData' : Array<InvoiceProcessingResult>,
}
export type ExternalBlob = Uint8Array;
export interface ExtractedFields {
  'subtotalAmount' : string,
  'invoiceDate' : string,
  'invoiceNumber' : string,
  'totalAmount' : string,
  'gstTaxId' : string,
  'vendorName' : string,
}
export interface InvoiceProcessingResult {
  'status' : { 'fail' : string } |
    { 'success' : null },
  'extractedFields' : [] | [ExtractedFields],
  'invoiceId' : bigint,
  'vendorName' : string,
}
export interface ProcessedInvoiceInput {
  'blob' : ExternalBlob,
  'filename' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VendorTemplate {
  'user' : Principal,
  'fieldMappings' : Array<[string, string]>,
  'vendorName' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInvoiceToBatch' : ActorMethod<
    [bigint, ExternalBlob, string],
    [] | [BatchInvoice]
  >,
  'archiveBatch' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'autoApplyVendorTemplateForBatch' : ActorMethod<[bigint, string], bigint>,
  'checkDuplicateInBatch' : ActorMethod<[bigint, string, string], boolean>,
  'createBatch' : ActorMethod<[], bigint>,
  'createVendorTemplate' : ActorMethod<
    [string, Array<[string, string]>],
    undefined
  >,
  'deleteVendorTemplate' : ActorMethod<[string], undefined>,
  'exportBatchData' : ActorMethod<[bigint, Array<string>], [] | [ExportData]>,
  'getBatchDetails' : ActorMethod<
    [bigint],
    [] | [{ 'batch' : Batch, 'invoices' : Array<BatchInvoice> }]
  >,
  'getBatchInvoices' : ActorMethod<[bigint], Array<BatchInvoice>>,
  'getBatches' : ActorMethod<[[] | [BatchStatus]], Array<Batch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExcelTemplateDetails' : ActorMethod<[bigint], [] | [ExcelTemplate]>,
  'getExcelTemplates' : ActorMethod<[], Array<ExcelTemplate>>,
  'getInvoiceDetails' : ActorMethod<[bigint], [] | [InvoiceProcessingResult]>,
  'getInvoices' : ActorMethod<[], Array<InvoiceProcessingResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorTemplate' : ActorMethod<[string], [] | [VendorTemplate]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listVendorTemplates' : ActorMethod<[], Array<VendorTemplate>>,
  'prepareExportData' : ActorMethod<
    [Array<bigint>, Array<[string, string]>],
    [] | [ExportData]
  >,
  'processBatchSequentially' : ActorMethod<
    [bigint, Array<ProcessedInvoiceInput>],
    [] | [Array<BatchInvoice>]
  >,
  'processInvoice' : ActorMethod<
    [ExternalBlob, string, string],
    InvoiceProcessingResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBatchInvoiceMapping' : ActorMethod<
    [
      bigint,
      bigint,
      {
        'subtotalAmount' : string,
        'invoiceDate' : string,
        'invoiceNumber' : string,
        'totalAmount' : string,
        'gstTaxId' : string,
        'vendorName' : string,
      },
    ],
    undefined
  >,
  'updateVendorTemplate' : ActorMethod<
    [string, Array<[string, string]>],
    undefined
  >,
  'uploadExcelTemplate' : ActorMethod<
    [ExternalBlob, string, Array<string>],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];