/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ExtractedFields = IDL.Record({
  'subtotalAmount' : IDL.Text,
  'invoiceDate' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'totalAmount' : IDL.Text,
  'gstTaxId' : IDL.Text,
  'vendorName' : IDL.Text,
});
export const BatchInvoice = IDL.Record({
  'extractedFields' : IDL.Opt(ExtractedFields),
  'invoiceId' : IDL.Nat,
  'isDuplicate' : IDL.Bool,
  'invoiceNumber' : IDL.Text,
  'batchId' : IDL.Nat,
  'vendorName' : IDL.Text,
  'isAutoMapped' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvoiceProcessingResult = IDL.Record({
  'status' : IDL.Variant({ 'fail' : IDL.Text, 'success' : IDL.Null }),
  'extractedFields' : IDL.Opt(ExtractedFields),
  'invoiceId' : IDL.Nat,
  'vendorName' : IDL.Text,
});
export const ExportData = IDL.Record({
  'columnMappings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'invoiceData' : IDL.Vec(InvoiceProcessingResult),
});
export const BatchStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const Time = IDL.Int;
export const Batch = IDL.Record({
  'status' : BatchStatus,
  'invoiceCount' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'batchId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExcelTemplate = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'userId' : IDL.Principal,
  'columnHeaders' : IDL.Vec(IDL.Text),
  'filename' : IDL.Text,
  'uploadDate' : Time,
});
export const VendorTemplate = IDL.Record({
  'user' : IDL.Principal,
  'fieldMappings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'vendorName' : IDL.Text,
});
export const ProcessedInvoiceInput = IDL.Record({
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInvoiceToBatch' : IDL.Func(
      [IDL.Nat, ExternalBlob, IDL.Text],
      [IDL.Opt(BatchInvoice)],
      [],
    ),
  'archiveBatch' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'autoApplyVendorTemplateForBatch' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'checkDuplicateInBatch' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'createBatch' : IDL.Func([], [IDL.Nat], []),
  'createVendorTemplate' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'deleteVendorTemplate' : IDL.Func([IDL.Text], [], []),
  'exportBatchData' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Opt(ExportData)],
      ['query'],
    ),
  'getBatchDetails' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({ 'batch' : Batch, 'invoices' : IDL.Vec(BatchInvoice) })
        ),
      ],
      ['query'],
    ),
  'getBatchInvoices' : IDL.Func([IDL.Nat], [IDL.Vec(BatchInvoice)], ['query']),
  'getBatches' : IDL.Func([IDL.Opt(BatchStatus)], [IDL.Vec(Batch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExcelTemplateDetails' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ExcelTemplate)],
      ['query'],
    ),
  'getExcelTemplates' : IDL.Func([], [IDL.Vec(ExcelTemplate)], ['query']),
  'getInvoiceDetails' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(InvoiceProcessingResult)],
      ['query'],
    ),
  'getInvoices' : IDL.Func([], [IDL.Vec(InvoiceProcessingResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendorTemplate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VendorTemplate)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listVendorTemplates' : IDL.Func([], [IDL.Vec(VendorTemplate)], ['query']),
  'prepareExportData' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Opt(ExportData)],
      ['query'],
    ),
  'processBatchSequentially' : IDL.Func(
      [IDL.Nat, IDL.Vec(ProcessedInvoiceInput)],
      [IDL.Opt(IDL.Vec(BatchInvoice))],
      [],
    ),
  'processInvoice' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text],
      [InvoiceProcessingResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBatchInvoiceMapping' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Record({
          'subtotalAmount' : IDL.Text,
          'invoiceDate' : IDL.Text,
          'invoiceNumber' : IDL.Text,
          'totalAmount' : IDL.Text,
          'gstTaxId' : IDL.Text,
          'vendorName' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'updateVendorTemplate' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'uploadExcelTemplate' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ExtractedFields = IDL.Record({
    'subtotalAmount' : IDL.Text,
    'invoiceDate' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'totalAmount' : IDL.Text,
    'gstTaxId' : IDL.Text,
    'vendorName' : IDL.Text,
  });
  const BatchInvoice = IDL.Record({
    'extractedFields' : IDL.Opt(ExtractedFields),
    'invoiceId' : IDL.Nat,
    'isDuplicate' : IDL.Bool,
    'invoiceNumber' : IDL.Text,
    'batchId' : IDL.Nat,
    'vendorName' : IDL.Text,
    'isAutoMapped' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvoiceProcessingResult = IDL.Record({
    'status' : IDL.Variant({ 'fail' : IDL.Text, 'success' : IDL.Null }),
    'extractedFields' : IDL.Opt(ExtractedFields),
    'invoiceId' : IDL.Nat,
    'vendorName' : IDL.Text,
  });
  const ExportData = IDL.Record({
    'columnMappings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'invoiceData' : IDL.Vec(InvoiceProcessingResult),
  });
  const BatchStatus = IDL.Variant({
    'active' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Time = IDL.Int;
  const Batch = IDL.Record({
    'status' : BatchStatus,
    'invoiceCount' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'batchId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExcelTemplate = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'userId' : IDL.Principal,
    'columnHeaders' : IDL.Vec(IDL.Text),
    'filename' : IDL.Text,
    'uploadDate' : Time,
  });
  const VendorTemplate = IDL.Record({
    'user' : IDL.Principal,
    'fieldMappings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'vendorName' : IDL.Text,
  });
  const ProcessedInvoiceInput = IDL.Record({
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInvoiceToBatch' : IDL.Func(
        [IDL.Nat, ExternalBlob, IDL.Text],
        [IDL.Opt(BatchInvoice)],
        [],
      ),
    'archiveBatch' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'autoApplyVendorTemplateForBatch' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'checkDuplicateInBatch' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'createBatch' : IDL.Func([], [IDL.Nat], []),
    'createVendorTemplate' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'deleteVendorTemplate' : IDL.Func([IDL.Text], [], []),
    'exportBatchData' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Opt(ExportData)],
        ['query'],
      ),
    'getBatchDetails' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({ 'batch' : Batch, 'invoices' : IDL.Vec(BatchInvoice) })
          ),
        ],
        ['query'],
      ),
    'getBatchInvoices' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BatchInvoice)],
        ['query'],
      ),
    'getBatches' : IDL.Func(
        [IDL.Opt(BatchStatus)],
        [IDL.Vec(Batch)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExcelTemplateDetails' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExcelTemplate)],
        ['query'],
      ),
    'getExcelTemplates' : IDL.Func([], [IDL.Vec(ExcelTemplate)], ['query']),
    'getInvoiceDetails' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InvoiceProcessingResult)],
        ['query'],
      ),
    'getInvoices' : IDL.Func([], [IDL.Vec(InvoiceProcessingResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendorTemplate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VendorTemplate)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listVendorTemplates' : IDL.Func([], [IDL.Vec(VendorTemplate)], ['query']),
    'prepareExportData' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Opt(ExportData)],
        ['query'],
      ),
    'processBatchSequentially' : IDL.Func(
        [IDL.Nat, IDL.Vec(ProcessedInvoiceInput)],
        [IDL.Opt(IDL.Vec(BatchInvoice))],
        [],
      ),
    'processInvoice' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text],
        [InvoiceProcessingResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBatchInvoiceMapping' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Record({
            'subtotalAmount' : IDL.Text,
            'invoiceDate' : IDL.Text,
            'invoiceNumber' : IDL.Text,
            'totalAmount' : IDL.Text,
            'gstTaxId' : IDL.Text,
            'vendorName' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'updateVendorTemplate' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'uploadExcelTemplate' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };